name: Deploy website cicd-tikunvn

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/cicd-git-action

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create production config
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          sed -i "s/'host' => 'localhost'/'host' => '$DB_HOST'/" libraries/config.php
          sed -i "s/'username' => 'root'/'username' => '$DB_USER'/" libraries/config.php
          sed -i "s/'password' => ''/'password' => '$DB_PASS'/" libraries/config.php
          sed -i "s/'dbname' => 'tikunvn'/'dbname' => '$DB_NAME'/" libraries/config.php

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_42184596
          password: ${{ secrets.INFINITYFREE_PASSWORD }}
          local-dir: ./
          server-dir: /htdocs/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/*.sql
            logs/**
            caches/**
            .env
