name: Deploy website cicd-tikunvn

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftpupload.net
          username: if0_42184596
          password: ${{ secrets.INFINITYFREE_PASSWORD }}
          local-dir: ./ # thư mục source code local
          server-dir: /htdocs/ # thư mục trên server
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
            config.php
